version: '3.9'
services:
  mongo:
    container_name: powder-mongodb-test
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: powder
    ports:
      - 27017:27017