version: '3.9'
services:
  devcontainer:
    container_name: powder-devcontainer
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    volumes:
      - ../:/app:cached
    network_mode: service:mongo
    command: sleep infinity

  mongo:
    container_name: powder-mongodb
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: powder
      MONGO_INITDB_ROOT_PASSWORD: powder
      MONGO_INITDB_DATABASE: powder

  mongo-express:
    container_name: powder-mongo-express
    image: mongo-express:1.0.2-20-alpine3.19
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: powder
      ME_CONFIG_MONGODB_ADMINPASSWORD: powder
      ME_CONFIG_MONGODB_URL: mongodb://powder:powder@powder:27017/

volumes:
  mongo-data:
    driver: local
